### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BorisHristovH** [Rebirth-of-the-Night/Rebirth-Of-The-Night#447] opened 2020-08-17 13:53 UTC
Jump height bonus from items/baubles inconsistent with Balloon bauble

**To Reproduce**
Steps to reproduce the behaviour:
Equip Balloon Bauble
Equip Cobalt Shield with Jump height modifier
Equip Emerald Ring with Jump height modifier
Jump

**Expected behavior**

To jump higher than 3 blocks with all those modifiers.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**
Actually the modifier from the ring gets ignored completely when Balloon is equipped, while the one from the cobalt shield overwrites the bonus from what i tested.

**Comment by democat3457** [comment] 2020-08-17 14:19
Duplicate of #112

**Closed by democat3457** 2020-08-17 14:19 UTC
