### ISSUE TITLE
[CRASH] Arrows fired into unloaded chunks via True Shot

### ISSUE THREAD

**Issue by RedChaos56** [Rebirth-of-the-Night/Rebirth-Of-The-Night#417] opened 2020-07-01 04:36 UTC
server will crash from a tipped arrow being fired
[crash-2020-07-01_14.21.59-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/4855702/crash-2020-07-01_14.21.59-server.txt)

**Comment by democat3457** [comment] 2020-07-01 15:53
Issue appears to be caused by an arrow trying to find entities in its path, but the arrow was fired into unloaded chunks. Did you fire the arrow (if so, which arrow?), or did a skeleton?

**Comment by RedChaos56** [comment] 2020-07-02 08:32
could true shot make that happen

**Comment by RedChaos56** [comment] 2020-07-02 08:42
true shot is not affected by gravity they just keep going

**Comment by RedChaos56** [comment] 2020-07-03 03:57
it was but with a normal arrow but bow had true shot

**Comment by democat3457** [comment] 2020-07-03 04:02
Can you reproduce it on a new arrow shot/new world?

**Comment by democat3457** [comment] 2020-07-03 04:02
Also, does it happen with different arrows?

**Comment by RedChaos56** [comment] 2020-07-03 04:21
on server or single player

**Comment by RedChaos56** [comment] 2020-07-03 04:24
well on single player everything stops block wont break chunks don't load but doesn't crash but server does

**Comment by RedChaos56** [comment] 2020-07-03 04:27
also other arrows do it to

**Comment by RedChaos56** [comment] 2020-07-03 04:30
no actually the single player crashes Minecraft you have to reopen the game

**Comment by RedChaos56** [comment] 2020-07-03 04:32
by the way the crash report was from my server thought you might just want to know

**Comment by democat3457** [comment] 2020-07-03 14:41
Does this happen on a reinstall as well?

**Comment by democat3457** [comment] 2020-07-22 20:20
Can't reproduce on dev with Mythril Bow that has True Shot, firing a Fuse Arrow into the distance.

**Comment by democat3457** [comment] 2020-09-10 20:46
Can anyone else reproduce this? Will close soon if not.

**Comment by DragarX** [comment] 2020-09-19 07:20
for me using trueshot doesn't crash but does cause massive lag if shooting into distance, i have to reset the whole game to fix it.

**Comment by democat3457** [comment] 2020-09-19 20:35
In that case, I'll close this issue for now and if it pops back up on 3.0, open a new GitHub issue or reopen this one.

**Closed by democat3457** 2020-09-19 20:35 UTC
Labels: needs testing, question
