### ISSUE TITLE
[BUG] Filtered Hopper not filtering ground netherrack (Progression Block)

### ISSUE THREAD

**Issue by IronEE** [Rebirth-of-the-Night/Rebirth-Of-The-Night#587] opened 2021-01-19 20:25 UTC
**Describe the bug**
Using a filtered hopper to filter ground netherrack into hellfire dust does not work, no matter if it has a chest underneath, an unfilled urn, or is unpowered. This causes progression into masterwork tier impossible, and soulsteel unobtainable.

**To Reproduce**
1) Build and power a filtered hopper
2) Place soul sand into filter slot
3) Throw ground netherrack on top and watch it fall through or go into internal inventory if urn or chest is underneath, producing no hellfire dust 

**Expected behavior**
Hellfire dust to be made and a full soul urn after 8 ground netherrack

**Screenshots**
Not needed to explain

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 Beta 2

**Additional context**
I also tried to filter soul beads too, and if I remember correctly it did not fill urns either

**Comment by democat3457** [comment] 2021-01-19 20:53
duplicate of #334

**Closed by democat3457** 2021-01-19 20:53 UTC
