### ISSUE TITLE
[CRASH] Using crowbar on refractory bricks causes client crash

### ISSUE THREAD

**Issue by Borregon** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1153] opened 2024-12-30 22:43 UTC
### Describe the crash

https://github.com/user-attachments/assets/4187d1b0-49f3-4c17-bd93-76e8d41ab0bd

### To Reproduce

1) Join multiplayer server on version 3.2.1b
2)Use crowbar on refractory bricks
3)Crash

### Crash Logs

[crash-2024-12-30_00.22.52-client.txt](https://github.com/user-attachments/files/18278169/crash-2024-12-30_00.22.52-client.txt)

### Modpack Version

3.2

### Server or singleplayer

Server

### Version the world was created on:

3.2

**Comment by KaleThyself** [comment] 2024-12-31 00:24
Duplicate of #1095.

**Closed by KaleThyself** 2024-12-31 00:24 UTC
