### ISSUE TITLE
[CRASH] Aether + ActualMusic Crash

### ISSUE THREAD

**Issue by zawayy** [Rebirth-of-the-Night/Rebirth-Of-The-Night#160] opened 2020-03-24 22:47 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
I crash when I'm in the Aether

**To Reproduce**
Go to the aether for like 5 min
**Crash Log**
https://paste.dimdev.org/matepuxire.makefile

**Info (please complete the following information):**
In singleplayer
World created in version 2.76.2 and the crash in the same versison

**Comment by CalaMariGold** [comment] 2020-03-31 05:58
So this is an issue caused by ActualMusic. A temporary fix is to remove Embassy.jar from the mods folder. I have reason to believe it might be crashing because MC is using the latest version of Java, when it should only be using Java 8.

Not much we can do about this right now. Need to wait on a fix from ActualMusic.

**Comment by wolfw3** [comment] 2020-03-31 19:16
> I have reason to believe it might be crashing because MC is using the latest version of Java, when it should only be using Java 8
Oddly enough, I had JDK SE 14 installed alongside JRE 8, and upon removing it Embassy would crash Minecraft before it finished starting up

**Comment by wolfw3** [comment] 2020-03-31 19:29
Can confirm, had JRE 8 along with JDK SE 14 installed. Upon uninstalling JDK, actualmusic works just fine. It seems that actualmusic itself may be trying to use the newer JDK, as I have JRE 8 set under MultiMC

**Comment by democat3457** [comment] 2020-05-07 00:58
Any update?

**Comment by CalaMariGold** [comment] 2020-05-07 01:03
I'm unsure how to go about this. Maybe tell all players to uninstall any newer JDK. The mod in question is not on CF and is not going to be updated

**Comment by democat3457** [comment] 2020-09-10 20:57
Fixed with soundtrack update.

**Closed by democat3457** 2020-09-10 20:57 UTC
Labels: mod bug

**Comment by Davoleo** [comment] 2020-09-11 13:40
Just wondering, will the soundtrack update be shipped together with the `1.3` release or will it be available as a separate update for ActualMusic before the release of 1.3?

**Comment by democat3457** [comment] 2020-09-11 17:02
The soundtrack update is already out, it was changed as soon as we knew (on the google drive).

**Comment by Davoleo** [comment] 2020-09-11 19:56
ok, thanks for letting me know
