### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by DorianZ2** [Rebirth-of-the-Night/Rebirth-Of-The-Night#777] opened 2021-06-13 20:54 UTC
**Describe the crash**
You know that mechanic when you right-click a fully grown crop, it automatically harvests and replants it? Well, in case of Nether Warts it causes crashes.

**To Reproduce**  
Right-click a fully grown nether wart plant.

**Crash Log**
[crash-2021-06-13_22.28.06-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6644631/crash-2021-06-13_22.28.06-client.txt)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [x] Server
   - [ ] Singleplayer (haven't tried)
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**
None.

**Comment by democat3457** [comment] 2021-06-13 20:55
known, dupe of #742

**Closed by democat3457** 2021-06-13 20:55 UTC
