### ISSUE TITLE
[BUG] Brewing stand consuming more items than required

### ISSUE THREAD

**Issue by Perforalia** [Rebirth-of-the-Night/Rebirth-Of-The-Night#594] opened 2021-01-22 21:56 UTC
**Describe the bug**
I placed three magic powders into the top slot of a brewing stand, in order to convert three logs of oak wood into magic wood. Instead of using up one magic powder as in the JEI recipe, it used all three.

**To Reproduce**
Acquire brewing stand, and try to brew magic wood with more than the required one magic powder

**Expected behavior**
Consumption of only one magic powder in the brewing process.

**Info:**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Comment by Kompreya** [comment] 2021-02-17 22:59
This will be fixed when I eventually add transformation recipes. This was added as a stand-in by, I think Sandwich, to help players get magic wood more easily, but was never my intention for magic wood to be craftable.

**Comment by democat3457** [comment] 2021-02-17 23:26
also thats probably a vanilla bug? its not used to taking in more than one item at the top

**Comment by KaleThyself** [comment] 2022-07-24 08:05
This is an issue because this recipe exists:
![image](https://user-images.githubusercontent.com/50285548/180638075-e81f9b85-1fb8-4f98-aba0-18c402819b0f.png)
If this recipe is removed, the issue is resolved and only one of the three magic powders would be used up. I believe it would be a proper band-aid fix until the intended feature of acquiring magic wood is implemented (unless it already is via the biome).

**Comment by democat3457** [comment] 2022-07-25 02:14
looks like the issue is that we accidentally swapped two parameters in the recipe 😳

**Comment by democat3457** [comment] 2022-07-25 02:15
nevermind i see the issue

**Closed** 2022-07-25 02:27 UTC
Labels: RotN bug, upcoming fix
