### ISSUE TITLE
Amphithere flying bug [BUG]

### ISSUE THREAD

**Issue by vicebison** [Rebirth-of-the-Night/Rebirth-Of-The-Night#503] opened 2020-11-05 23:57 UTC
**Describe the bug**

If you are riding a tamed Amphithere and you land in water, you will be ejected and the amphithere will proceed to infinitely fly/float upwards even if you are not within the chunks.
**To Reproduce**
Be riding an Amphitere, have it set to "Sitting" then land in water, and doing so you will be ejected.

**Expected behavior**
The dragon will simply float on the water. 

**Screenshots**

![image](https://user-images.githubusercontent.com/70415886/98309499-9f1e8680-1f98-11eb-8623-d8904fff67b4.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

Best way to get them back down is by using creative mode. which is fkin annoying.

**Comment by kil0byt3** [comment] 2021-01-11 19:40
hard to modify ourselves, and I&F isn't updating anymore for 1.12 if I recall? We'll have a look either way post-3.0 to check if this still happens

**Comment by KaleThyself** [comment] 2022-07-24 07:21
I can confirm that this issue still occurs along with #740 in v.3.1.1a. 
Perhaps keep this as the original issue and mark the other as duplicate?

**Comment by democat3457** [comment] 2022-07-25 01:59
the other one has more information, so closing this as duplicate of #740

**Closed by democat3457** 2022-07-25 01:59 UTC
Labels: mod bug, needs testing, planned fix
