### ISSUE TITLE
[BUG] Green Schist brick slabs transforming into Basalt brick slabs

### ISSUE THREAD

**Issue by Dinoscan** [Rebirth-of-the-Night/Rebirth-Of-The-Night#511] opened 2020-11-28 19:58 UTC
**Describe the bug**
Green Schist brick slabs from the Underground Biomes mod become Basalt brick slabs from the same mod when mined with any pickaxe (tested with stone, iron, bronze and diamond pickaxes).

**To Reproduce**
Place a single Green Schist brick slab (doesn't matter which half of the block it is placed) and mine it with any pickaxe.
**Expected behavior**
Green Schist brick slab is supposed to drop as a Green Schist brick slab when mined.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5

**Additional context**
When placing two Green Schist brick slabs to make a single block, they behave normally and drop as Green Schist when mined.

**Comment by democat3457** [comment] 2020-11-28 21:21
duplicate of #362

**Closed by democat3457** 2020-11-28 21:21 UTC
