### ISSUE TITLE
[BUG] Guidebook not working on Linux

### ISSUE THREAD

**Issue by CyborgPotato** [Rebirth-of-the-Night/Rebirth-Of-The-Night#536] opened 2021-01-09 01:02 UTC
Patchouli Book Not Working on Linux

Create 1.12.2 Instance in MultiMC
Install Starred Version of Forge
Clone Master repo. of Rebirth of the Night and copy inner contents into .minecraft of instance
Open SP game, open Survivors Handbook and notice it's empty

**Expected behavior**
Patchouli book to contain contents of Survivors Handbook

**Screenshots**
![image](https://user-images.githubusercontent.com/10701143/104078259-22539700-51eb-11eb-8e3e-1f9d29cd1828.png)
![image](https://user-images.githubusercontent.com/10701143/104078262-267fb480-51eb-11eb-9cab-c249e356b941.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA 2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 BETA 2

**Additional context**
Running OpenSuse Tumbleweed
Java OpenJDK 8
Logs attached

[latest.log](https://syzygial.cc/ROTN/latest.log)
[debug.log](https://syzygial.cc/ROTN/debug.log)

**Comment by Hubry** [comment] 2021-01-09 17:35
I suspect that this is caused by Linux paths being case sensitive.

The book is located in `./patchouli_books/SurvivorsHandbook`, which assigns it a resource location `patchouli:survivorshandbook`, because in 1.12 these are silently lowercased. Then when the time to actually load entries comes, it tries to crawl entries under `./patchouli_books/survivorshandbook`, which succeeds on Windows because that's not case sensitive, but fails on Linux.

The solution is to rename the directory - note that it might need an intermediate step of naming the directory something completely different because Git might have a hard time detecting it.

**Comment by Kompreya** [comment] 2021-01-09 17:50
This will need to be fixed on our end. Thanks for bringing this to our attention - lowercase it is, then!
In the meantime, can you rename your `.minecraft\patchouli_books\SurvivorsHandbook` to `.minecraft\patchouli_books\survivorshandbook` (all lowercase) to see if it fixes the issue?

**Comment by CyborgPotato** [comment] 2021-01-09 18:15
Yes changing the folder `.minecraft\patchouli_books\SurvivorsHandbook` to `.minecraft\patchouli_books\survivorshandbook` fixes the issue and allows the guidebook to function properly

**Comment by Kompreya** [comment] 2021-01-09 18:46
Wonderful! We will make sure things are lowercased in the future to ensure compat with other OSes

**Closed by Kompreya** 2021-01-09 18:46 UTC
Labels: RotN bug, documentation
