### ISSUE TITLE
[BUG] The Well makes a second block of water next to it.

### ISSUE THREAD

**Issue by PDMephisto** [Rebirth-of-the-Night/Rebirth-Of-The-Night#622] opened 2021-02-02 04:28 UTC
**Describe the bug**
When using a bucket to pull water from the well, it will produce another block of water next to it or on top of it depending on where the cursor is. 

**To Reproduce**
Try pulling water from the bucket and it makes the second water block every time. 

**Expected behavior**
The expected behavior is that it fills the bucket and that's all. 

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: Beta 3.0 v3
 - Server or Singleplayer: Single player 
 - Version the world was created on: Beta 3.0 v3

**Additional context**

**Comment by 5431-programming** [comment] 2021-02-02 04:50
Duplicate of #591

**Comment by 5431-programming** [comment] 2021-02-02 04:50
frick wrong account lmao

**Comment by democat3457** [comment] 2021-02-02 04:51
kek

**Closed by democat3457** 2021-02-02 04:51 UTC
