### ISSUE TITLE
Duping glitch[BUG]

### ISSUE THREAD

**Issue by BASSbanane** [Rebirth-of-the-Night/Rebirth-Of-The-Night#743] opened 2021-04-29 12:20 UTC
**Describe the bug**
 Beewax duping with mochi recipe

**To Reproduce**  
Steps to reproduce the behavior: craft mochi with beewax

**Expected behavior**
 instead of consuming it, adding beewax (the more beewax is stacked, the more will be added,can stack above 64) and consuming all water bottles that are stacked, the rice will stay the same or even dupe himself.

**Screenshots**
 
![Rebirth of the Night v3 0 BETA 5 29 04 2021 14_16_57](https://user-images.githubusercontent.com/83405914/116549637-05f07d00-a8f6-11eb-89e5-8d720c5d2cf9.png)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

**Comment by democat3457** [comment] 2021-04-29 14:44
duplicate of #712

**Closed by democat3457** 2021-04-29 14:44 UTC
