### ISSUE TITLE
[CRASH] newest version won't load

### ISSUE THREAD

**Issue by GwnPandaBeer** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1043] opened 2023-06-10 14:45 UTC
### Describe the crash

i downloaden the newest ROTN version and it didnt load, just gave me a screen that some shit was downloading. waited for more then 2 hours but nothing changed.

### Crash Logs

?

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

### Other...

i tried playing on the 3.0.1a and that worked, just the 3.1.1a didnt

**Comment by EliteMeats** [comment] 2023-07-19 10:10
How to fix this bug currently:

1 download preview OptiFine 1.12.2 HD U G6 pre1 from https://www.optifine.net/downloads
2 download Sound-Physics-1.12.2-1.0.10-1.jar from https://github.com/djpadbit/Sound-Physics/releases/tag/1.0.10-1 and put both in the mods folder of the modpack
3 go into the config folder then mod-director folder and delete the .json files inside
4 launch the modpack and it should open fully

This bug has been fixed in the next update, 3.2.0.

**Closed by EliteMeats** 2023-07-19 10:10 UTC
Labels: upcoming fix, mod update needed, planned fix, critical

**Comment by EliteMeats** [comment] 2023-07-19 10:17
Duplicate of #1037

**Comment by Justuuz** [comment] 2023-07-20 02:10
I experiment like 6 hours for a alternative solution, cause old one doesnt work
How to fix this bug currently (updated):

1 put it in to the browser "https://optifine.net/adloadx?f=preview_OptiFine_1.12.2_HD_U_G6_pre1.jar" and download it
2 download Sound-Physics-1.12.2-1.0.10-1.jar from 
"https://github.com/djpadbit/Sound-Physics/releases/download/1.0.10/Sound-Physics-1.12.2-1.0.10.jar" 
and put both in the mods folder of the modpack
3 go into the config folder then mod-director folder and delete only the optifine.url.json file inside
4 launch the modpack and it should open fully

The linked datas are from the "mod-director" folder, if u open the two .json datas of optifine and sound-physics with editor u can copy the URL links and download the 2 mods

**Comment by HotelSierra08** [comment] 2023-07-29 12:04
i deleted both and it worked
