### ISSUE TITLE
[BUG] Player recieves fire damage from blazes regardless of attack

### ISSUE THREAD

**Issue by Layla1228** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1020] opened 2023-02-08 22:53 UTC
### Describe the bug

Regardless of whether I use a sword or a ranged weapon such as snowballs or a bow, there is about a 1 in 3 chance of receiving fire damage despite no blaze fireballs being shot.

### To Reproduce

Going to the Nether and Fighting a Blaze, be melee or ranged

### Expected behavior

According to the discord, this should only be happening when using melee. 

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

### Other...

Replicated on both singleplayer and multiplayer.

**Comment by KaleThyself** [comment] 2023-02-09 00:27
Duplicate of #990; this issue may be closed.

**Closed** 2023-02-09 01:43 UTC
