### ISSUE TITLE
[BUG] gneiss overgrown gets invisible

### ISSUE THREAD

**Issue by SussyMan111** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1110] opened 2024-06-21 16:45 UTC
### Describe the bug

gneiss overgrown become invisible on entering world with connected textures on

### To Reproduce

use connect textures > leave from minecraft (maybe world) > join in any world and its broken

### Screenshots

![bandicam 2024-06-21 19-43-13-272](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/assets/151395170/6db33a08-d522-42ed-b811-df061d977c6d)

### Modpack Version

3.2

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

**Comment by Foreck1** [comment] 2024-06-21 16:57
Can you attempt to reload resources with F3+T? This will take around 5 minutes and will freeze your game, but it should fix it for this and any new world you create.

**Comment by SussyMan111** [comment] 2024-06-21 17:14
that helped but if it works like changing settings then i need to do it anytime i restart minecraft (i will close this if no more problem even on restart)

**Comment by Foreck1** [comment] 2024-06-21 18:39
This shouldn't be the case. Once assets are reloaded once, the issue (caused by IDs shifting around) should be fixed permanently for that world you are in as well as newly created worlds.
In any case, this bug is caused by an interaction between JEID and Optifine which we cannot fix in any way and has been present for years. While I regret that is the case, there's no likely solution to be added, so I'm closing this issue as archive.

**Closed by Foreck1** 2024-06-21 18:39 UTC
