### ISSUE TITLE
[Breaking Quartzite Brick Slabs turns them into Andesite Brick Slabs]

### ISSUE THREAD

**Issue by Slapstickguy** [Rebirth-of-the-Night/Rebirth-Of-The-Night#434] opened 2020-07-26 12:52 UTC
**Describe the bug**

**To Reproduce**
-Break Quartzite Brick Slab with Pickaxe

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by democat3457** [comment] 2020-07-26 16:34
Duplicate of #362

**Closed by democat3457** 2020-07-26 16:34 UTC
