### ISSUE TITLE
[BUG] Paper Custom Enchanted Tools

### ISSUE THREAD

**Issue by TBiscuit1** [Rebirth-of-the-Night/Rebirth-Of-The-Night#450] opened 2020-08-19 04:03 UTC
**Describe the bug**
Enchanted Tools that has custom texture (like bows and diamond tools) will be 2D

**To Reproduce**
1 - Enchant a tool/bow that has custom texture when enchanted (depend of enchant, ex: efficiency 4/5 for diamond pickaxe)
2 - Look at the item in the hand, it's now "paper" like
3 - If you do F5, you can see that the outline is missing but the 2 faces are there

**Expected behavior**
Not to do that of course!

**Screenshots**
I'm too laz... too busy to show a screeshot

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: Both
 - Version the world was created on: 2.77

**Additional context**
I accidentally find out which mod cause this glitch, it's texfix, sadly, the mod didn't got updated for more then 2y so there is no chance of a fix

3 solution
1 - Hope that the mod creator fix it
2 - Remove the mod
3 - Create or Find a mod with a similar feature

**Comment by democat3457** [comment] 2020-08-19 04:07
Is this a duplicate of your other issue #395 @TBiscuit1 ?

**Comment by TBiscuit1** [comment] 2020-08-19 14:30
oooh I forgot that one, yes, but this time I found the mod that cause this, gonna close the other one

**Comment by kil0byt3** [comment] 2020-12-10 14:41
None of your 3 solutions are ideal; closing due to rarity of issue (good to have this tracked however.)

**Closed by kil0byt3** 2020-12-10 14:41 UTC
