### ISSUE TITLE
[BUG] Stuck in the void after loading the world

### ISSUE THREAD

**Issue by somebush** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1046] opened 2023-07-15 13:00 UTC
### Describe the bug

After teleporting to the village through the way stone, leaving the world and loading the world, my player is stuck in the void and cannot do anything. In this state, the world around is not visible, the ancient atlas is also empty, but the coordinates are visible. You can't move, you can't open inventory and use items from the hotbar. Messages sent to the chat are not visible. The time of day is changing. Steve's head is shaking.
Also, in the stuck state in the upper left corner of the screen, I see the exact time in numbers to the right of the classic time scale. I don't see it in normal game.

### To Reproduce

I stole a way stone from a nearby village, installed it in my house, gave it a name using the = sign and Cyrillic characters =Дом=. I used it a couple of times for sure, I don’t remember exactly how many, the teleport was working properly. But once I teleported to another village on the eve of the second invasion, after which I played for several minutes, left the world and entered again.

### Expected behavior

I teleport to the village without any problems. I exit the world and boot into it without problems.

### Screenshots

![BUG2](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/assets/132480428/ba3a4e51-1423-435c-9408-6ac40a47e330)
![BUG1](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/assets/132480428/502a98c5-7ebc-4e48-9b29-b28ebfae91c0)

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

### Other...

I played this build on another playthrough some time ago. There I flew off to explore the world on a hippogriff and made some backups of my save. The last few pieces were corrupted - they were affected by the same problem with getting stuck in the abyss after loading the world. I had to use an older save to see now how much progress I made in the last game.

**Comment by somebush** [comment] 2023-07-15 13:19
I replaced the game save with an older one, but with the same way stones - teleportation from the house to the village was successful, without errors. This error appeared in one of the last saves. But I don't know what caused it.

**Comment by somebush** [comment] 2023-07-15 13:45
The problem is not with the way stone, but with certain chunks on which the village stands. I figured it out by teleporting there via cheats. The last time I played there, my game crashed due to lack of RAM, after which I teleported home through the way stone. I hope there is a way to somehow recreate specific chunks.

**Comment by KaleThyself** [comment] 2023-07-15 21:17
Possible duplicate of #849. Temporary solution: Update Village Names to v.4.4.1a.

**Comment by somebush** [comment] 2023-07-16 14:03
Thanks a lot! The error is gone with the new version.
Fundamentally, version 4.4.1a is needed, the other will not work?
The village has changed its name. It was Krmeecred, it became Qiszu. Clan - House Lumens

**Comment by somebush** [comment] 2023-07-17 08:34
Oh no! I ran through the world, discovering new lands, and there was no waystone in the new village. It also looked like a village from newer versions of vanilla minecraft.

**Comment by sneetsnart** [comment] 2023-07-17 08:41
yes.... we don't have waystones in our pack and the villages are supposed to look like newer ones

**Comment by somebush** [comment] 2023-07-17 20:05
There is an idea: before exploring new parts of the world, you need to use the old broken version of the mod. And when you are done with the research and are about to return to the broken village - use the new version of the mod with the wrong (new) villages. It will be very painful because the game takes about 5 minutes to load.

**Comment by somebush** [comment] 2023-07-17 21:15
This problem can affect everyone, make the game 100% dead. Why developers are not in a hurry to solve it?

**Comment by KaleThyself** [comment] 2023-07-17 21:30
> This problem can affect everyone, make the game 100% dead. Why developers are not in a hurry to solve it?

Please refrain from using the Github Issues page as a chat forum. It has been explained in the Discord server several times that updates are rolled out when a number of other changes are made to the modpack. As for this issue at hand, it has already been fixed in the next update via mod update.

**Comment by EliteMeats** [comment] 2023-07-19 10:07
As Kale said, duplicate of issue #849. Closing issue due to this

**Closed** 2023-07-19 10:09 UTC
Labels: duplicate, planned fix
