### ISSUE TITLE
[BUG] Limestone Stairs upsidedown show up as missing textures in WAILA

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#592] opened 2021-01-21 05:51 UTC
**Describe the bug**
Limestone stairs have a missing texture when placed upside down and viewed on the bottom left hand corner where WAILA is. 

**To Reproduce**
1. Place limestone stairs upside down. 
2. Look at it and see the missing texture showing up on the bottom left hand corner of the screen. 

**Expected behavior**
Expected the stairs to show up as normal limestone stairs on WAILA. 

**Screenshots**
![2021-01-20_21 46 02](https://user-images.githubusercontent.com/50285548/105285599-8f5f1900-5b69-11eb-8915-03e5d867ffe2.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 Beta 2

**Additional context**
Not tested with other stairs.

**Comment by CalaMariGold** [comment] 2021-01-22 00:50
I'm gonna mark this as a duplicate of #362. We'll just use that issue for all UGB issues

**Closed by CalaMariGold** 2021-01-22 00:50 UTC
