### ISSUE TITLE
armor, main hand, baubles deleting when killed by player[BUG]

### ISSUE THREAD

**Issue by BASSbanane** [Rebirth-of-the-Night/Rebirth-Of-The-Night#746] opened 2021-05-01 19:33 UTC
**Describe the bug**
 look title

**To Reproduce**  
Steps to reproduce the behavior: kill yourself or others( no command)

**Expected behavior**
 armor, main hand, baubles deleted and items dropped, no death will be created

**Screenshots**

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [x] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

**Comment by democat3457** [comment] 2021-05-02 04:10
possible duplicate of #524

**Comment by KaleThyself** [comment] 2022-07-18 19:03
Not enough information/followup—mark as duplicate of #524 and close(?)

**Closed** 2022-07-18 19:04 UTC
Labels: duplicate, needs testing, 3.0 BETA
