### ISSUE TITLE
Stymphalian arrows dupe (maybe all kinds of arrows too idk)

### ISSUE THREAD

**Issue by z57333** [Rebirth-of-the-Night/Rebirth-Of-The-Night#754] opened 2021-05-08 04:15 UTC
When I was playing, I was testing out stymphalian arrows, shooting them on the wall, etc. Then I noticed the number of arrows I had (originally 12) was going up, to 13, 14, then 15. It was weird and it didn't happen every time I picked up the arrows again. Weird bug, very beneficial. Just asking for this to be reported and aware of.

**Comment by democat3457** [comment] 2021-05-09 23:41
What bow (and enchants?), what version, and did you have any potion effects?

**Comment by z57333** [comment] 2021-05-10 22:20
And no, I did not have any potion effects from anything except the well fed effect because I was eating some steak.

**Comment by democat3457** [comment] 2021-05-11 03:11
Is this effect replicable with a different bow (different material)?

**Comment by z57333** [comment] 2021-05-11 05:06
I haven't tried it, as I'm afraid that the server admin will ban me if I do
this again, and he and I are already on not-so-good terms. But, I will get
back to you once I have tested it in singleplayer. Also, the server admin
sees everything on the aternos console, so yeah... he's been keeping an eye
out on not so ordinary things.

**Comment by KaleThyself** [comment] 2022-07-18 19:27
Presumably a duplicate of #857; may close due to not enough info/invalid post.

**Comment by democat3457** [comment] 2022-07-18 19:39
not a duplicate as the bow does not have Back to the Chamber, supposedly

**Comment by democat3457** [comment] 2022-07-18 19:39
however, yea this does have an invalid format and is also very old

**Closed by democat3457** 2022-07-18 19:39 UTC
Labels: awaiting information, invalid
