### ISSUE TITLE
[BUG] pied piper spawning without gamestage unlocked

### ISSUE THREAD

**Issue by Ninjayatsu** [Rebirth-of-the-Night/Rebirth-Of-The-Night#768] opened 2021-05-31 20:47 UTC
**Describe the bug**

was mining in a cave, only had iron gear, no game stages unlocked, heard the pied piper, went into spectator and there it was

**To Reproduce**  

Steps to reproduce the behavior: wait for it to spawn while in a deep cave, it spawned in the grassy cave biome.

**Expected behavior**

no pied piper spawning

**Screenshots**

![2021-05-31_16 42 13](https://user-images.githubusercontent.com/66919658/120240944-ccca6600-c22f-11eb-8704-9299a803acba.png)

**Info (please complete the following information):**

 - Modpack Version:

   - 3.0 BETA 5

 - Server or Singleplayer:

   - [ ] Singleplayer
 
 - Version the world was created on:

   - [ ] 3.0 BETA 5

**Additional context**

N/A

**Comment by KaleThyself** [comment] 2021-05-31 21:08
Difficult mobs can spawn rarely as intended. (Can close this issue.)

**Closed** 2021-06-07 01:36 UTC
Labels: Works as Intended
