### ISSUE TITLE
[BUG] Volcanic Gas can follow a player even through a Return potion back to your house thousands of blocks away

### ISSUE THREAD

**Issue by FamiliarPings** [Rebirth-of-the-Night/Rebirth-Of-The-Night#862] opened 2022-05-01 20:59 UTC
### Describe the bug

A friend and I were mining out an area, that had a volcanic gas pocket in it. When he teleported home with a return potion to get something, the gas... went with him and filled his house. We have no idea why this happened, but the gas continued to teleport to him for nearly 30 seconds before stopping.
![image](https://user-images.githubusercontent.com/85465423/166164389-ff5bddf4-30b1-4b56-bc97-3296bd1ce4ea.png)

### To Reproduce

Use a return potion while standing in a pocket of volcanic gas

### Expected behavior

Uhm... no gas?

### Modpack Version

3.0.1

### Server or singleplayer

Server

### Version the world was created on:

3.0.1

**Comment by KaleThyself** [comment] 2023-01-15 08:47
Was the gas dropped into their inventory via water breaking it? If so, then yes, it's completely intended.

**Comment by democat3457** [comment] 2023-01-16 21:52
Seeing as it got labeled with a Works As Intended, closing

**Closed by democat3457** 2023-01-16 21:52 UTC
Labels: Works as Intended, 3.0.x
