### ISSUE TITLE
[BUG] Infinite Mochi Glitch

### ISSUE THREAD

**Issue by ann00b** [Rebirth-of-the-Night/Rebirth-Of-The-Night#837] opened 2022-04-07 20:56 UTC
### Describe the bug

When crafting mochi, while it consumes the water and gives back the glass correctly, the recipe actually duplicates the rice and sugar used to create it.

### To Reproduce

create the mochi recipe in your inventory, using sugar or honeycomb, but have **more than one rice, sugar or honeycomb** in the crafting grid. Depending on the amount of ingredient, it will either simply not consume it, or actually duplicate it.
![image](https://user-images.githubusercontent.com/17811060/162302408-1fa65d16-8902-4c5b-98fc-03a43b0053a7.png)

### Expected behavior

The recipe should consume the rice, sugar, and water, but return the glass bottle.

### Screenshots

![image](https://user-images.githubusercontent.com/17811060/162302062-e8ec0e02-ced7-441c-a2f7-00c6c0b60568.png)
after just making about 16 mochi, i had an insane amount of these ingredients

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by ann00b** [comment] 2022-04-07 21:02
![image](https://user-images.githubusercontent.com/17811060/162305876-c03d2135-84bf-4d7e-8be4-e3b36244405d.png)
got another good screenshot of its effects

**Comment by iEatShadows** [comment] 2022-04-07 22:42
Yep its still the same glitch from beta 5 iirc. Beta 5 version #712

**Comment by ann00b** [comment] 2022-04-07 23:12
oh shoot, so it is.

**Comment by democat3457** [comment] 2022-04-11 14:02
Duplicate of #712

**Closed** 2022-04-11 14:02 UTC
