### ISSUE TITLE
[BUG] smoker deletes sweet potatoes

### ISSUE THREAD

**Issue by elipol02** [Rebirth-of-the-Night/Rebirth-Of-The-Night#555] opened 2021-01-11 05:02 UTC
**Describe the bug**
Sweet potatos are deleted inside of a smoker after cooking, with both wood and charcoal

**To Reproduce**
Put charcoal in the bottom and sweet potato in the top
**Expected behavior**
After cooking the sweet potatoes, I expected there to be baked sweet potatoes in the right side of the smoker

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 2
 - Server or Singleplayer: single player 
 - Version the world was created on: 3.0 beta 2

**Additional context**

**Comment by kil0byt3** [comment] 2021-01-11 20:13
seems to be working in dev, likely fixed in next beta

**Comment by CalaMariGold** [comment] 2021-01-15 03:58
Also occurs with raw calamari (heh). Can't seem to reproduce with any other food other than calamari and sweet potato.

**Comment by CalaMariGold** [comment] 2021-01-15 04:02
> mods.futuremc.Smoker.addRecipe(calamari, cookedCalamari);

The CT script for the smoker doesn't work. Will require a PR

**Comment by democat3457** [comment] 2021-01-15 20:47
But a PR for what? Do *all* of the `Smoker.addRecipe()` lines not work?

**Comment by CalaMariGold** [comment] 2021-01-15 20:51
Yes there's only 2

**Comment by CalaMariGold** [comment] 2021-02-03 02:25
fixed in beta 4

**Closed by CalaMariGold** 2021-02-03 02:25 UTC
Labels: 3.0 BETA, mod bug
