### ISSUE TITLE
[BUG] Villages not loading correctly

### ISSUE THREAD

**Issue by cyantifical** [Rebirth-of-the-Night/Rebirth-Of-The-Night#537] opened 2021-01-09 02:50 UTC
**Describe the bug**
In some of the village buildings (namely the kings one) there is an invisible block behind the doors that disappears once the guards and king spawn, which can sometimes happen late (regular villagers are unaffected).

**To Reproduce**
1. Enter a village
2. Maybe don't trigger the guards spawning? (I think this was due to me not hitting the "sweet spot" of the village where it triggers their spawn.
3. Attempt to enter the king's building, there is an invisible block in the way of the door
4. There will be no guards, or king in the building.

**Expected behavior**
To walk straight through the door, and for there to be guards and the king.

**Screenshots**
[Standing on the invisible block](https://imgur.com/mOQB1fS)

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 beta

**Additional context**
I went into creative and could not see the boundary of a block at all, so I don't believe its a barrier block. I could be wrong, however.

**Comment by kil0byt3** [comment] 2021-01-11 19:46
we'll have to see what we can do. The mod dev is inactive so we need to see if we can fix this ourselves. linked to #538

**Comment by Fate1098** [comment] 2021-01-12 05:17
Same issue on my world. Invisible blocks in both the entrances to the king's building, in front of the king's throne, back left of throne room, and front right of throne room. No king or guards present in the building.

Image of bottom floor with redstone blocks directly above invisible blocks in entrances:
![image](https://user-images.githubusercontent.com/70050676/104272323-7b793000-5462-11eb-806b-95e4396f4a60.png)

Image of second floor with redstone block above corner invis block and redstone blocks surrounding invis blocks in front of throne:
![image](https://user-images.githubusercontent.com/70050676/104272537-e7f42f00-5462-11eb-8662-2b3666fd4780.png)

Image of second floor with redstone block above corner invis block:
![image](https://user-images.githubusercontent.com/70050676/104272572-08bc8480-5463-11eb-9f46-ea89e306a259.png)


Modpack Version: 3.0 Beta 2
Server or Singleplayer: Singleplayer
Version the world was created on: 3.0 Beta 2

**Comment by CalaMariGold** [comment] 2021-01-12 05:19
Did you pregen ur world? Also lords dont spawn in raided villages.

**Comment by Fate1098** [comment] 2021-01-12 05:20
Sorry about the images (can't seem to get them to work). No, I did not pregen.

**Comment by Fate1098** [comment] 2021-01-12 05:24
Also, I can remove the invisible blocks just like any other 'ghost block' by placing a block over it and removing it.

**Comment by cyantifical** [comment] 2021-01-12 05:32
My world wasn't pregenned, and the village wasn't raided - the lord (and guards) spawned in after walking around for a little bit. Regular ol' singleplayer world started in beta 1. After that everything was fine, except for the old being attacked randomly bug.

**Comment by Fate1098** [comment] 2021-01-12 06:32
Pieces of the king's building are generating in villages (ranges from just the towers to half the building) even though there is already a full 'king's building' in the village.

Short clip showing pieces of the building (sorry for the quality---still trying to figure out how to capture things):

![71682949922d1a6dfc5259c561dcf4e4](https://user-images.githubusercontent.com/70050676/104277975-7a013500-546d-11eb-8762-da557ca0c9b6.gif)


Modpack Version: 3.0 Beta 2
Server or Singleplayer: Singleplayer
Version the world was created on: 3.0 Beta 2

**Comment by democat3457** [comment] 2021-01-12 15:32
> Sorry about the images (can't seem to get them to work).

Fyi, F2 is hotkey for screenshot and copies to clipboard (not sure if you realized that for your successive images)

**Comment by CalaMariGold** [comment] 2021-01-15 04:32
I've been to dozens, probably a hundred villages at this point and have never seen this error. I can't reproduce this.

**Comment by CalaMariGold** [comment] 2021-01-22 02:07
Should be fixed next beta build

**Closed by CalaMariGold** 2021-01-22 02:07 UTC
Labels: 3.0 BETA, cannot reproduce, mod bug, needs testing
