### ISSUE TITLE
[BUG] Smoker deleting apples

### ISSUE THREAD

**Issue by cha0sbuster** [Rebirth-of-the-Night/Rebirth-Of-The-Night#678] opened 2021-03-03 07:43 UTC
**Describe the bug**
When I attempt to make Baked Apples in a Smoker, the apples just get voided.

**To Reproduce**
1. Put apple in smoker.
2. Put fuel in smoker.
3. ???
4. Profit. (....well, actually, *loss* but y'know.)

**Expected behavior**
My apple to become baked, rather than disappear.

**Screenshots**
Not sure a screenshot explains anything. :P

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA 4
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 BETA 4

**Additional context**
While looking around the GitHub for this and another issue, I found #555 ? It could be a similar cause (broken CT script).

**Comment by democat3457** [comment] 2021-03-03 14:33
Hmm we don't mention apples at all in the Smoker script... This is probably either inherited from furnace or added by the mod itself. In any case, it's probably not quite a duplicate of #555, and shouldn't be closed.

**Comment by democat3457** [comment] 2021-04-06 16:42
can reproduce on dev singleplayer

**Closed** 2021-04-15 06:00 UTC
Labels: 3.0 BETA, mod bug
