### ISSUE TITLE
[BUG] Filling a flimsy bucket with water from a well simultaneously places a water block

### ISSUE THREAD

**Issue by barnabywalters** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1006] opened 2022-10-30 14:39 UTC
### Describe the bug

When right-clicking on a well with a flimsy bucket to fill it with water, the bucket gets filled as expected, but a water block is simultaneously placed on the side of the well.

### To Reproduce

1. Make a well and bucket
2. Right-click on the well with the bucket
3. Observe that the bucket is full but the well has sprung a leak

### Expected behavior

The bucket should be filled without also placing a water block in the world.

### Screenshots

![2022-10-30_15 26 22](https://user-images.githubusercontent.com/968350/198884613-8cba7b6c-0a37-4cc1-9542-47b9f865e5d0.png)

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

**Comment by democat3457** [comment] 2022-10-31 01:20
duplicate of #591

**Closed by democat3457** 2022-10-31 01:20 UTC

**Comment by barnabywalters** [comment] 2022-10-31 01:21
Oops, missed that one in my search somehow. Good to know it’s known, apologies for the dupe.
