### ISSUE TITLE
[BUG] Filtered Hopper does not craft Hellfire dust

### ISSUE THREAD

**Issue by Fate1098** [Rebirth-of-the-Night/Rebirth-Of-The-Night#571] opened 2021-01-13 03:55 UTC
**Describe the bug**
Filtered hopper does not create Hellfire dust even though it is hooked up to a working windmill, has soul sand as a filter, and has ground netherrack thrown on top of it (both the single hellfire and 8 hellfire recipe does not work).

**To Reproduce**
1.) Connect a filtered hopper to a working windmill (connect axle to one of four sides of the filtered hopper).
2.) Put soul sand in the filter box (single box above larger section) by right clicking the filtered hopper.
3.) (for 8 hellfire) Connect an urn to the bottom of the filtered hopper.
4.) Throw ground netherrack on top of the filtered hopper.

**Expected behavior**
The filtered hopper turns the ground netherrack into hellfire dust and, in the case that you use an urn, creates a soul urn.

**Screenshots**
Picture of connection between filtered hopper and axle:
![image](https://user-images.githubusercontent.com/70050676/104404244-d6249180-551f-11eb-894a-4a9e23b188b2.png)

Picture of the inside of the filtered hopper:
![image](https://user-images.githubusercontent.com/70050676/104404337-0835f380-5520-11eb-9f7c-ad8fcf51d10b.png)

NOTE: due to a snow storm during the creation of the screenshots, the windmill is not working. Therefore, the axle is not turning and the cog within the filtered hopper is not brown (indicating that a working axle is connected to it). Even when the axle is turning, the recipes DO NOT work. 

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Akliz Server
 - Version the world was created on: 3.0 Beta 2

**Additional context**
Multiple people on the server tried creating the hellfire dust but was unsuccessful. Instead, the ground netherrack goes straight through the hopper when throw on top of it.

**Comment by democat3457** [comment] 2021-01-13 03:59
Basically a duplicate of #334

**Closed by democat3457** 2021-01-13 03:59 UTC
