### ISSUE TITLE
[BUG] Duplicate item when i break MHF_WSkeleton

### ISSUE THREAD

**Issue by Ezonight** [Rebirth-of-the-Night/Rebirth-Of-The-Night#579] opened 2021-01-14 08:41 UTC
**Describe the bug**
Duplicate item when i break MHF_WSkeleton.

**To Reproduce**
On SMP, break a MHF_Skeleton with bronze axe. It will loot 2 MHF_WSkeleton. Action can be repeat on MHF_WSkeleton.

**Info (please complete the following information):**
 - Modpack Version: ROTN Beta 2
 - Server or Singleplayer: Server 
 - Version the world was created on: 1.12 with ROTN Beta 2 server

**Comment by CalaMariGold** [comment] 2021-02-03 02:03
duplicate of #535

**Closed by CalaMariGold** 2021-02-03 02:03 UTC
Labels: 3.0 BETA
