### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sickb0unz** [Rebirth-of-the-Night/Rebirth-Of-The-Night#642] opened 2021-02-14 02:24 UTC
**Describe the bug**
Dropping ground netherrack in filtered hopper with soulsand as filter don't transform it in hellfire dust, it doesn't do anithing. Nothing change powered or not, with urn or not.

**To Reproduce**
Drop ground netherrack in filtered hopper with soulsand as filter.

**Expected behavior**
Transforming ground netherrack in hellkfire dust.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: RotN 3.0 BETA 3
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: RotN 3.0 BETA 3

**Additional context**
I tryied in 3 different worlds but the result is the same.

**Comment by CalaMariGold** [comment] 2021-02-14 02:29
dupe of #571

**Closed by CalaMariGold** 2021-02-14 02:29 UTC

**Comment by democat3457** [comment] 2021-02-14 03:17
(actually a dupe of #334 because otherwise we're just chaining duplicate issues)
