### ISSUE TITLE
[CRASH] Twilight generating server crash 

### ISSUE THREAD

**Issue by BansheeUwU** [Rebirth-of-the-Night/Rebirth-Of-The-Night#647] opened 2021-02-16 00:39 UTC
my server crashed when me and a friend were trying to go through the twillight portal for the first time i asked for help and was told "Ok so there is an exception in the world when doing a tick update. When loading the twilight forest, the game is attempting to spawn random mobs I think." 
**To Reproduce**

**Crash Log**
https://pastebin.com/fkJZ8fQ7

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta
 - Server 
 - Version the world was created on: 1.12

**Additional context**

**Comment by SenatorSupreme** [comment] 2021-03-20 04:25
A temp fix for this will be implemented in beta 5.

**Comment by SenatorSupreme** [comment] 2021-03-20 04:28
Actually, duplicate of #640

**Closed by SenatorSupreme** 2021-03-20 04:28 UTC
Labels: 3.0 BETA, upcoming fix
