### ISSUE TITLE
Advanced Enchantment Table Enchant cannot be removed while testing out new enchants.

### ISSUE THREAD

**Issue by JartanFTW** [Rebirth-of-the-Night/Rebirth-Of-The-Night#366] opened 2020-06-02 22:19 UTC
With the Advanced Enchantment Table, it allows you to select any enchant you desire. Say you put a non-enchanted pickaxe in and move the slider to Efficiency 3. Even without pressing the little book icon to finalize the changes, you cannot revert the Efficiency 3 to nothing without taking the pickaxe out and putting it back in.

1. Give yourself about 1000 xp to allow the following steps.
2. Take a brand new pickaxe with no enchants and place it in the Advanced Enchantment Table.
3. Move the Efficiency slider to the right.
4. Attempt to move the Efficiency slider to the left.

The slider will not allow you to move it to the left, even before finalizing the selected enchants with the book button.

https://gyazo.com/57d2cf3f16029179db891b259b502ac2

 - Modpack Version: v2.77.4
 - Server or Singleplayer: Server
 - Version the world was created on: v2.77.4

**Comment by democat3457** [comment] 2020-06-02 22:30
What pickaxe is it?

**Comment by democat3457** [comment] 2020-06-02 22:32
Oh, I see... Nevermind. The issue is already reported [here](https://github.com/Epoxide-Software/Enchanting-Plus/issues/130)

**Comment by CalaMariGold** [comment] 2021-01-20 22:55
Closing. True enchantment table will be getting removed in the future

**Comment by democat3457** [comment] 2021-01-21 01:15
then we shouldnt close the issue if its not technically fixed then, so people wont end up reporting this on 3.0

**Comment by democat3457** [comment] 2021-03-07 23:36
Fixed by repairing the item to full durability. Unfortunate workaround, but it works that way.

**Closed by democat3457** 2021-03-07 23:36 UTC
Labels: mod bug, planned fix
