### ISSUE TITLE
[BUG] Error Message when activating dense redstone ore

### ISSUE THREAD

**Issue by Fate1098** [Rebirth-of-the-Night/Rebirth-Of-The-Night#557] opened 2021-01-11 05:45 UTC
**Describe the bug**
An error message appears constantly when entering a cave. Seems to appear more often when activating dense redstone ore (redstone lights up). Multiple people in the server seem to run into the issue when activating the dense redstone ore so it is most likely the issue. 

**To Reproduce**
Steps to reproduce the behavior: Activate a dense redstone ore in a cave.

**Expected behavior**
 Errors should not appear when activating dense redstone ore.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Akliz Server
 - Version the world was created on: 3.0 Beta 2

**Additional context**
Here is the error report:
[Error Report.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5794187/Error.Report.txt)

**Comment by democat3457** [comment] 2021-01-11 15:32
Is this reproducible on other worlds?

**Comment by kil0byt3** [comment] 2021-01-11 19:33
From discord, another user also experiencing same issue. Safe to say needs testing by rotn team

**Comment by CyborgPotato** [comment] 2021-01-11 19:33
Reproducible in my world.

**Comment by CyborgPotato** [comment] 2021-01-11 19:36
Also, might be poor memory will edit if I am wrong, but for me it was not dense redstone ore, rather the dense redstone crystals

**Comment by Foreck1** [comment] 2021-01-11 19:38
Dense redstone is getting placed by COFH world instead of by Pyrotech itself. There may be a chance that's it's because of that, but I seriously doubt so, since the error doesn't seem to be related with generation specifically.

**Comment by Fate1098** [comment] 2021-01-11 19:39
Yeah sorry for not being specific. It was the crystal formations that gave the error for me.

**Comment by CalaMariGold** [comment] 2021-01-22 05:16
Only occurs on servers. Still an issue on beta 3

**Comment by CalaMariGold** [comment] 2021-03-31 18:01
Created issue on Pyrotech GitHub, awaiting response

**Comment by codetaylor** [comment] 2021-04-01 17:38
Fixed in Pyrotech `1.5.10`

**Closed** 2021-04-01 18:53 UTC
Labels: 3.0 BETA, mod bug, mod update needed
