### ISSUE TITLE
[CRASH] Shiftclicking in a stonecutter

### ISSUE THREAD

**Issue by mpenley79** [Rebirth-of-the-Night/Rebirth-Of-The-Night#492] opened 2020-10-12 18:49 UTC
**Describe the crash**

**To Reproduce**
1. Add 64 Soapstone to stonecutter
2. select bricks
3. Shift click bricks output

**Crash Log**
When I attempted to do this it failed , even after full client restart.

**Info (please complete the following information):**
 - Modpack Version: 2.77.5 
 -  Singleplayer:
 - Version the world was created on: 2.77.5

**Additional context**
Single clicking bricks from the output works, and seems to be stable.

**Comment by democat3457** [comment] 2020-10-12 18:52
Duplicate of #24

**Closed by democat3457** 2020-10-12 18:52 UTC
