### ISSUE TITLE
[CRASH] Frozen Fiend's Iceologer mob causes a vanillafix crash when killed

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#719] opened 2021-03-25 23:59 UTC
**Describe the crash**
Killing an Iceologer with a glass sword causes a crash log to be created. 

**To Reproduce**  
1. Summon an Iceologer. 
2. Kill the Iceologer with a glass sword. 
3. View the crash log created. 

**Crash Log**
[Get link failed]
https://pastebin.com/zk5QaN33

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 2.77.5
   - [X] 3.0 BETA 4
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [X] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [X] 3.0 BETA 4
   - [ ] Other:

**Comment by democat3457** [comment] 2021-03-26 00:02
duplicate of #539

**Closed by democat3457** 2021-03-26 00:02 UTC
