### ISSUE TITLE
[BUG] Can't pick up barrels

### ISSUE THREAD

**Issue by ThreeForths** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1117] opened 2024-06-23 21:59 UTC
### Describe the bug

Barrels can't be picked up while Chests can.

### To Reproduce

Shift Right click a chest with nothing in either hand, and you will pick it up.

Shift Right Click a barrel in the same manor, and it doesn't allow you to move it.

### Expected behavior

You should be able to move both Chests and Barrels by shift rightclicking them with open hands.

### Screenshots

![image](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/assets/56747631/e2b7572a-c1d7-47cb-8296-d32a9f47711c)
![image](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/assets/56747631/61a4677e-cae2-4c9e-9a4b-1260da2101d7) -- When you shift right click a barrel it just opens the barrel.

### Modpack Version

Other

### Server or singleplayer

Server

### Version the world was created on:

Other

### Other...

3.2.1b

**Comment by iEatShadows** [comment] 2024-06-23 22:49
Not a bug cause it depends on which barrel. (there are 3 types with "barrel" in the name) I am assuming you are trying to pick up the **futuremc:barrel** ? if so, you can add it to the carryon whitelist doing these steps -->https://youtu.be/FlniK6rQUb8

**Comment by iEatShadows** [comment] 2024-06-23 22:57
Its possibly an over sight, lucky its and easy change/fix

**Comment by ThreeForths** [comment] 2024-06-24 02:46
> Its possibly an over sight, but at least its an easy change/fix.

Yup, I have already done this server side. Just wanted to report it incase it was an oversight

**Comment by democat3457** [comment] 2024-06-25 05:05
Fixed with a45165d.

**Closed by democat3457** 2024-06-25 05:05 UTC
