### ISSUE TITLE
[BUG] can't access nether despite correct gamestages

### ISSUE THREAD

**Issue by xtulio07** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1107] opened 2024-06-19 03:50 UTC
### Describe the bug

I and a buddy have both killed the harvester (twice), but we still cant get into the nether, I've checked both our gamestages (they contained "killedharvester"), deleted and recreated the files, restarted the server, moved and relit the portal, and tested in another world (it works there). The portal is acting the same way it would if we didn't killed the harvester, staying stuck on the portal warping effect.

### To Reproduce

Multiplayer server
Kill harvester
Make portal
Enter?

### Expected behavior

To enter the nether as intended

### Modpack Version

3.2

### Server or singleplayer

Server

### Version the world was created on:

3.2

### Additional context

v3.2.1b

**Comment by KaleThyself** [comment] 2024-06-21 19:35
Duplicate of #976; Try using the gamestage command to give yourself the `enterednether` gamestage.

**Closed** 2024-06-21 19:36 UTC
Labels: duplicate
