### ISSUE TITLE
[BUG] Animals are flying

### ISSUE THREAD

**Issue by Randoom17** [Rebirth-of-the-Night/Rebirth-Of-The-Night#713] opened 2021-03-22 19:43 UTC
**Describe the bug**
Animals are flying above the water. They're jumping and can't stop. Also, some mobs are really fast in the water, like bandits. If I'm not wrong, it works in jungle-like biomes, cause I found it out in a jungle.

**To Reproduce**
Idk. Just put someone in the water and wait.

**Expected behavior**
Animals will start jump without stopping

**Screenshots**
![2021-03-23_00 20 53](https://user-images.githubusercontent.com/81188002/112048708-82ae6f80-8b70-11eb-88c8-52843d2d8593.png)
![2021-03-23_00 20 55](https://user-images.githubusercontent.com/81188002/112048715-85a96000-8b70-11eb-9bcf-fa09905c4050.png)
![2021-03-23_00 21 02](https://user-images.githubusercontent.com/81188002/112048716-8641f680-8b70-11eb-997b-b0578dd69315.png)
![2021-03-23_00 21 28](https://user-images.githubusercontent.com/81188002/112048717-8641f680-8b70-11eb-940f-c57443f7ae78.png)
![2021-03-23_00 21 44](https://user-images.githubusercontent.com/81188002/112048722-86da8d00-8b70-11eb-9bd0-6d060e278731.png)

**Info (please complete the following information):**
3.0 v.4
Singleplayer:
3.0 v.4

**Additional context**
Once i tried to catch a chameleon. He got damage from landing when i put him on the ground. But it didn't work next time and a chameleon was intact

**Comment by democat3457** [comment] 2021-03-22 19:44
Duplicate of #623

**Closed by democat3457** 2021-03-22 19:44 UTC
