### ISSUE TITLE
[BUG] Archimedes Screw is uncraftable

### ISSUE THREAD

**Issue by FamiliarPings** [Rebirth-of-the-Night/Rebirth-Of-The-Night#860] opened 2022-04-30 04:22 UTC
### Describe the bug

Attempting to create the pattern out of any ingot will instead make the Luranin Brick type of that ingot, instead of the Archimedes Screw
![2022-04-30 at 12 21 AM](https://user-images.githubusercontent.com/85465423/166090729-0625abbb-0d6f-41ca-9ce3-b9d41996ac02.png)
![2022-04-30 at 12 21 AM](https://user-images.githubusercontent.com/85465423/166090737-e782f4e4-25fd-4821-8f05-2d29be87a2bc.png)

### To Reproduce

Attempt to craft the Achimedes Screw with any ingot that is applicable

### Expected behavior

The Archimedes Screw appearing in the crafted slot

### Modpack Version

3.0.1

### Server or singleplayer

Server

### Version the world was created on:

3.0.1

**Comment by democat3457** [comment] 2022-04-30 04:24
duplicate of #855

**Closed by democat3457** 2022-04-30 04:24 UTC
