### ISSUE TITLE
[BUG] Gold dupe on v. 3.1.0

### ISSUE THREAD

**Issue by klayiz** [Rebirth-of-the-Night/Rebirth-Of-The-Night#925] opened 2022-07-05 15:59 UTC
### Describe the bug

Sometimes, after something has finished smelting in a blast furnace and I've taken it out, the blast furnace starts smelting nothing into gold ingots. I've seen it smelt from 2 to 5 ingots.

### To Reproduce

To reproduce this bug/dupe, you have to put fuel and a few pieces of something smeltable into a blast furnace, for example, coal and ore respectively. After all the ore has been smelted into ingots, you have to immediately take the ingots out of the furnace, and the furnace should start smelting nothing into gold ingots.

### Expected behavior

Obviously, I expected the blast furnace to simply stop smelting since there was nothing left to smelt.

### Screenshots

![image](https://user-images.githubusercontent.com/108750244/177368563-ccf5b01f-ed8a-464f-8b9d-39f8793fafda.png)

### Modpack Version

3.1.0

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.0

### Additional context

I'm not sure, but I suppose that you have to take out the smelted items before the fuel runs out for the bug to happen, because when I take out the ingots after the fuel ran out it wouldn't start making gold ingots.

**Comment by democat3457** [comment] 2022-07-05 16:18
Duplicate of #850

**Closed by democat3457** 2022-07-05 16:18 UTC
