### ISSUE TITLE
[CRASH] game crashed, after looking at a player zombie

### ISSUE THREAD

**Issue by PDMephisto** [Rebirth-of-the-Night/Rebirth-Of-The-Night#665] opened 2021-02-27 02:19 UTC
**Describe the crash**
I zoomed in on a player zombie riding a spider and the game screen went white and crashed

**To Reproduce**

**Crash Log**
https://haste.antti.codes/madorunixu.mccrash

**Info (please complete the following information):**
 - Modpack Version: beta 4
 - Server or Singleplayer:  Singleplayer
 - Version the world was created on: 1.12v

**Additional context**

**Comment by democat3457** [comment] 2021-02-27 02:21
:| its been a known crash for ages - duplicate of #296

**Closed by democat3457** 2021-02-27 02:21 UTC
