### ISSUE TITLE
[CRASH] Something, possibly Animania, causing freezes on loading/saving and corrupting world files

### ISSUE THREAD

**Issue by MDMeaux** [Rebirth-of-the-Night/Rebirth-Of-The-Night#791] opened 2021-08-08 20:18 UTC
**Describe the crash**

Occasionally, when Save and Exiting from a Singleplayer world, the game will freeze completely on 'Shutting Down Internal Server'. I have tried leaving it for upwards of an hour and nothing happens, I eventually have to kill the game from task manager.  If I try to reload the game and open the same save, the game freezes while loading the world, and again, I have to kill the game. Loading the same save from an older backup has worked, but eventually the game crashes again. The same issue has happened to me on multiple separate save files. 

**To Reproduce**  

This only happens occasionally, I'm not sure how to replicate it consistently. It just seems to happen randomly sometimes when I save and exit a singleplayer (survival) world. 

**Crash Log**

The game doesn't technically 'crash', so there isn't a crash report generated, but here are some of the singleplayer logs from when the freeze happens:

[2021-08-07-6.log](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6951395/2021-08-07-6.log)
[2021-08-08-4.log](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6951390/2021-08-08-4.log)
[2021-08-08-5.log](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6951391/2021-08-08-5.log)
[2021-08-08-6.log](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6951392/2021-08-08-6.log)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

As can be seen from the logs, every time this freeze happens, the most recent messages are something to do with an error to do with Animania. In most of the cases I've seen it seems to be relating to rabbits but I think there was one relating to cows as well.

**Comment by democat3457** [comment] 2022-03-12 05:34
Since this doesn't seem to be replicable easily, I'll close this for now. If you can reliably reproduce this, then feel free to reopen - else, it seems like an edge case.

**Closed by democat3457** 2022-03-12 05:34 UTC
Labels: mod bug, needs testing, 3.0 BETA
