### ISSUE TITLE
[BUG] Every block of leaves broken with shears is dropping me 64 leaves(beta 4)

### ISSUE THREAD

**Issue by kdrop056** [Rebirth-of-the-Night/Rebirth-Of-The-Night#700] opened 2021-03-11 20:38 UTC
description: see title
reproduce: break leaves with shears(have not tested other types of shears or leaves, it may just be oak leaves)
expected: get 1 leaf block per break
info: singleplayer beta 4 world
![2021-03-11_15 27 41](https://user-images.githubusercontent.com/79732160/110851911-abd12500-827f-11eb-8e4c-ed2062306d84.png)
edit: seeing as there is a stack of 5 leaves of a different type, my guess is that it is an oak leaves issue

**Comment by democat3457** [comment] 2021-04-06 16:51
cannot reproduce on dev singeplayer

**Comment by democat3457** [comment] 2021-04-14 19:07
does it happen on a new world and/or reinstall

**Comment by democat3457** [comment] 2022-03-12 05:36
Since it doesn't seem to be reproducible, I'll close this.

**Closed by democat3457** 2022-03-12 05:36 UTC
Labels: needs testing, cannot reproduce, 3.0 BETA
