### ISSUE TITLE
[BUG] Toroquest bug with bandit lords not spawning inside the castle

### ISSUE THREAD

**Issue by Betsees** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1027] opened 2023-03-06 20:04 UTC
### Describe the bug

When going into a bandit lords castle, the bandit lord is not at his throne, but surrounded in stone around 20 blocks behind his throne.

### To Reproduce

1. Accept a bandit lord quest
2. Go to the bandit lords castle
3. Observe where the bandit lord is

### Expected behavior

The bandit lord should be at his throne

### Screenshots

![2023-03-07_00 21 45](https://user-images.githubusercontent.com/122879558/223218036-72f21303-67db-4e5e-82d2-ffbdab2eedda.png)
![2023-03-07_00 20 28](https://user-images.githubusercontent.com/122879558/223218231-699fc243-b30b-4dc7-a9e7-9b3d138844e3.png)

the first one is on a server
![2023-03-07_00 55 58](https://user-images.githubusercontent.com/122879558/223218113-9b3f7fbe-ad17-4f5f-8ff8-bd5a56087c5d.png)
![2023-03-07_00 55 41](https://user-images.githubusercontent.com/122879558/223218270-ddb0161c-27ad-465c-bca3-3c2eda99f0d7.png)

the second one is on a single player world to test

### Modpack Version

3.1.1a

### Server or singleplayer

Server, Singleplayer

### Version the world was created on:

3.1.1a

### Additional context

this has happened to me 3 times, 2 times on the server and once on the test world, idk if it can be reproduced or not. i dont have any other mods downloaded

**Comment by KaleThyself** [comment] 2023-03-06 21:53
I recommend commenting on #974 and adding the findings there instead since this is more or less a duplicate of the same issue.

**Comment by Betsees** [comment] 2023-03-07 10:21
Done, u can close this thread now. i would like to add that in 974 they specifically said theres no bass bar for bandit so maybe its not the same bug

**Closed** 2023-03-11 05:02 UTC
