### ISSUE TITLE
[BUG] Xp duplication

### ISSUE THREAD

**Issue by VoidlingGeneral** [Rebirth-of-the-Night/Rebirth-Of-The-Night#36] opened 2020-01-23 22:35 UTC
So basicaly i found out that if you kill youself after you have spent some xp levels, you will get some of it back, itw a bit weird but it can happen in two ways, either youll respawn with the levels or your droped xp orb will give you more back.
To reproduce 
you just have to do this 
1. spend your levels via enchantment table or anvil.
2. i just shot myself with a bow untill i died
3. i either respawned with extra levels or there were large xp orbs around where i died

I first found out on maris server, and also managed to reproduce on singleplayer. modpack version 2.74

I have no idea what could have caused this but the first time it happened i managed to gain more levels than i had before i spent it ( i had 35 levels spent untill i had 4 and after death i respawned with 46) but after a few tries i wasint able to get more levels than i began with, it would give less and less. might add a video later when i have time

**Comment by VoidlingGeneral** [comment] 2020-01-23 22:58
https://youtu.be/4-aJR9yJ7co
here i recreate the bug on a newly created world on 2.74
also to add i dont know if you have to kill yourself or something else can do it to happen,
thats just how i did it accidentally

**Comment by CalaMariGold** [comment] 2020-01-24 23:52
Seems like some issue with Quark where it isn't technically spending the levels. Or could be an issue with Corpse Complex, I don't really know. Kairyuu, can you look into this?

**Comment by CalaMariGold** [comment] 2020-02-10 20:06
We still haven't been able to reproduce this, but I've seen other players have this issue too. In 2.75.2, we reduced the XP you get back from death at an attempt to at least minimize this issue.

**Comment by HeyItsKairu** [comment] 2020-02-13 00:25
CorpseComplex appears to be the cause, but it is highly random and very difficult to reproduce. I have only seen two instances of this working.

**Comment by kil0byt3** [comment] 2020-04-20 18:03
Opened https://github.com/TheIllusiveC4/CorpseComplex/issues/33. Waiting.

**Comment by SandwichHorror** [comment] 2020-09-10 21:17
We know the cause. But the choice is not an easy one. Which way, western man?

**Comment by CalaMariGold** [comment] 2020-09-29 00:59
We can revisit this issue when we do an enchanting rework.

**Comment by SekretOne** [comment] 2021-02-28 19:53
@kil0byt3 I see the CorpseComplex issue was closed in January after some discussion- is this a fixed or won't fix?

**Comment by kil0byt3** [comment] 2021-02-28 20:12
still haven't tested to see if it exists but we've changed death mechanics multiple times since then so I am unsure

**Comment by democat3457** [comment] 2021-02-28 20:16
btw what sandwich was referring to is [this](https://discord.com/channels/620840315498004480/697887114993467392/753724315786280980)

**Comment by democat3457** [comment] 2021-03-07 23:28
*should* be fixed since learning was disabled a heckin while ago, reopen if this occurs again

**Closed by democat3457** 2021-03-07 23:28 UTC
Labels: critical, mod bug, needs testing, planned fix
