### ISSUE TITLE
[BUG] Game window freezes at 95% complete

### ISSUE THREAD

**Issue by Foreck1** [Rebirth-of-the-Night/Rebirth-Of-The-Night#4] opened 2020-01-01 00:29 UTC
The game will get stuck for some people at 95%. Fixed by any of the following:

- Minimize the game
- Optifine must be installed
- VSYNC must be disabled

Responsible mod: Optifine probably

**Comment by CalaMariGold** [comment] 2020-01-14 02:04
Also fixed by increasing RAM to 4-6gb.

**Comment by democat3457** [comment] 2020-05-06 23:37
not much we can do about this if its optifine though?

**Comment by SandwichHorror** [comment] 2020-09-10 20:56
This also happens whenever I run out of disk memory due to other processes - I don't think it can be reliably reproduced enough to be a bug with OUR pack specifically

**Comment by SekretOne** [comment] 2021-02-28 19:41
@Foreck1 this is a pretty dated issue- and it sounds like the source of your problem was limited resources.

Recommendation is that you have `4 gb` of RAM on `2.X` version, and `6 gb` if you are doing 3 or running 2.X with optifine and the music pack (3 has optifine and music bundled, hence the spec boost).

I'm closing this issue just as a clerical act, but comment here if you still have outstanding problems related to this and we can reopen it.

**Closed by SekretOne** 2021-02-28 19:41 UTC
Labels: needs testing

**Comment by kil0byt3** [comment] 2021-02-28 20:10
hey @Foreck1 make sure you have enough ram for the modpack. ;)
