### ISSUE TITLE
[BUG] Filtered Hopper not working

### ISSUE THREAD

**Issue by caramelliaa** [Rebirth-of-the-Night/Rebirth-Of-The-Night#563] opened 2021-01-12 00:27 UTC
**Describe the bug**
filtered hopper from betterwithmods doesn't work with filtering ground netherrack to get hellfire, basically locking progression (The recipes are still shown in JEI correctly)

**To Reproduce**
Steps to reproduce the behavior: Place a Filtered Hopper down, putting a soul sand in the filter slot, then drop Ground Netherrack on top of it. The ground netherrack will be sucked into the hopper like vanilla hoppers instead of filtering it (if there is an urn underneath) or just go through the hopper to the block below (if there isn't an urn underneath). 

**Expected behavior**
The netherrack should be filtered into Hellfire Dust and make funky ghast noises in the process, creating a soul urn if 8 netherrack is filtered

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Server and singleplayer
 - Version the world was created on: 3.0 Beta 2

**Comment by kil0byt3** [comment] 2021-01-12 01:31
thank you for the report! We've been tracking this one for a long time. Appreciate your writeup, I'll close this one though in favour of the previous one for tracking reasons. Duplicate of #334

**Closed by kil0byt3** 2021-01-12 01:31 UTC
