### ISSUE TITLE
[BUG] Hunter Illager death problem

### ISSUE THREAD

**Issue by JJuniorJr** [Rebirth-of-the-Night/Rebirth-Of-The-Night#667] opened 2021-02-27 16:40 UTC
**Describe the bug**
Killed a hunter illager with my fists soon after spawning in a new world and got this warning of possible world corruption

![hunterillagerissue](https://user-images.githubusercontent.com/48772725/109393505-200ae080-78f0-11eb-8b06-5a95cf6670f5.png)

as well as a link to this page

https://haste.antti.codes/erububujiq.mccrash

**To Reproduce**
Create new world and punch hunter illager to death.

**Expected behavior**
The illager to die and nothing bad happens

**Screenshots**
See above

**Info (please complete the following information):**
 - Modpack Version: v 3.0 Beta 4 hotfix 1
 - Server or Singleplayer: Single Player
 - Version the world was created on: v 3.0 Beta 4 hotfix 1

**Additional context**
Dont really know anything else

**Comment by democat3457** [comment] 2021-02-27 19:49
oh this is the same crash that you get from killing the black death and other illagers

problem with arcane world

**Comment by democat3457** [comment] 2021-03-26 00:02
duplicate of #539

**Closed by democat3457** 2021-03-26 00:02 UTC
Labels: 3.0 BETA
