### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by GoopisG** [Rebirth-of-the-Night/Rebirth-Of-The-Night#461] opened 2020-09-07 12:58 UTC
Unusual Zombie knocking on door.  Player opened door and swung once at zombie before crash.  Personal world not online.  Windmill, mill, saw, and turntable working in immediate vicinity.

**Crash Log**
[crash-2020-09-07_04.16.12-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5181924/crash-2020-09-07_04.16.12-client.txt)

**Info (please complete the following information):**
-  2.77.5
 - Singleplayer
 - 1.12.2

**Additional context**

**Comment by democat3457** [comment] 2020-09-07 15:33
Hi, yes, it's a crash between Zombie Players and Neat. Remove Neat, kill the zombie player, and put Neat back in.

**Comment by democat3457** [comment] 2020-09-07 15:34
Also it's a duplicate of #296

**Closed by democat3457** 2020-09-07 15:34 UTC
Labels: cantfix, mod bug
