### ISSUE TITLE
[BUG] Marble brick slab drops Rhyolite brick slab after breaking it

### ISSUE THREAD

**Issue by wenderccc** [Rebirth-of-the-Night/Rebirth-Of-The-Night#500] opened 2020-10-28 17:28 UTC
Marble brick slab drops Rhyolite brick slab instead of Marble brick  slab

**To Reproduce**
1. Place Marble brick slab
2. Break it
3. Get Rhyolite brick slab as drop

**Expected behavior**
1. Place Marble brick  slab
2. Break it
3. Get Marble brick slab as drop

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: v2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: v2.77.5

**Additional context**
N/A

**Comment by democat3457** [comment] 2020-10-28 18:22
Duplicate of #362

**Closed by democat3457** 2020-10-28 18:22 UTC
