### ISSUE TITLE
Particles for cauldron not appearing

### ISSUE THREAD

**Issue by Darqxs** [Rebirth-of-the-Night/Rebirth-Of-The-Night#967] opened 2022-07-26 06:39 UTC
### Describe the bug

When you try to get Lunar water from a cauldron the particles don't always show up but you can still throw Lunar quintessence in to get lunar water and sometimes it doesn't even work at all.

### To Reproduce

Place down a Cauldron and put water in it. Nothing can be above the cauldron and then you need to wait out the night. If you don't see particles then throw the quintessence in. Either the particles will appear or they won't it's kinda random.

### Expected behavior

I expected to see particles then throw quintessence in.

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

**Comment by democat3457** [comment] 2022-07-26 06:49
Semi-dupe of #963, keep it in there please

**Closed by democat3457** 2022-07-26 06:49 UTC
