### ISSUE TITLE
[BUG] Clipping the player into blocks while riding a hippogryph causes you to appear dismounted sometimes

### ISSUE THREAD

**Issue by YamiryuuNoKage** [Rebirth-of-the-Night/Rebirth-Of-The-Night#820] opened 2022-02-08 11:16 UTC
**Describe the bug**

Clipping into blocks with your face while riding a hippogryph sometimes causes you to ghost dismount. This makes it look like you have been dismounted as you are no longer visually on the mount. However, the game still considers you mounted as pressing the dismount key will drop you next to the hippogryph. This is extremely terrifying, especially in the aether.

**To Reproduce**  

Spawn in a hippogryph, ride it into a ceiling a few times (like a floating island or a cave ceiling)

**Expected behavior**
I expect to be able to hit blocks with my face, take suffocation damage normally while remaining seated on my mount, both visually and technically.

**Screenshots**

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x ] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [x ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [ x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

**Comment by KaleThyself** [comment] 2022-07-24 23:42
This is technically a duplicate of #503.

**Comment by democat3457** [comment] 2022-07-25 01:59
Duplicate of #740

**Closed by democat3457** 2022-07-25 01:59 UTC
Labels: mod bug, 3.0 BETA
