### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nomkie** [Rebirth-of-the-Night/Rebirth-Of-The-Night#999] opened 2022-10-18 02:11 UTC
### Describe the bug

Im not able to pick up stuff with the carry on mod

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

**Comment by KaleThyself** [comment] 2022-10-18 03:12
Duplicate of #907; please close this issue.

**Closed** 2022-10-18 15:44 UTC
