### ISSUE TITLE
[CRASH] Randomly Crashing while in multiplayer for no reason I can tell

### ISSUE THREAD

**Issue by capio13** [Rebirth-of-the-Night/Rebirth-Of-The-Night#266] opened 2020-04-19 00:47 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
It happens randomly whenever I am playing, I have allocated 6 gbs to the modpack and sometimes it just randomly infinitely freezes(Even after 20 minutes it wouldn't unfreeze) when im on multiplayer, not sure if it happens on single player too.

**To Reproduce**
Happens randomly, no known way I know to reproduce

**Crash Log**
https://paste.ee/p/Rqxeq (MultiMC Link)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by bboy122** [comment] 2020-05-07 15:48
**Describe the crash**
It happens randomly whenever I am playing, I have allocated 4096 mb to the modpack (i only have 8gb of ram) and sometimes it just randomly freezes(and then closes) when I'm on multiplayer, not sure if it happens on single player too.  It appears to happen more often in the aether region, and also after some play time (not before roughly 20 minutes). I have tried varying the ram up to 6 GB but it doesn't seem to improve it really.

**To Reproduce**
If i play i will always get a crash eventually (sometimes varies 20-60 mins approximately).

**Crash Log**
[crash-2020-04-23_20.40.04-client.zip](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4594007/crash-2020-04-23_20.40.04-client.zip)

**Info (please complete the following information):**

Modpack Version: 2.77.1
Server or Singleplayer: Server
Version the world was created on: 2.77.1

**Additional context**
i noticed it occurs less often on the old version of java (version 1.8.051) but more often on 1.8.251 (64 bit versions).

**Comment by bboy122** [comment] 2020-05-13 03:29
[hs_err_pid12372.log](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4619668/hs_err_pid12372.log)
 
had the same crash again on modpack version 2.77.2.1

**Comment by democat3457** [comment] 2020-05-13 04:17
> **Crash Log**
> [crash-2020-04-23_20.40.04-client.zip](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4594007/crash-2020-04-23_20.40.04-client.zip)

Regarding this, most of the crash logs appear to be about getting a null entity, getting a null tile entity, or, the case of the last one, getting a null sound effect. No solution yet, just some debugging.

**Comment by democat3457** [comment] 2020-05-13 04:18
> [hs_err_pid12372.log](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4619668/hs_err_pid12372.log)
> 
> had the same crash again on modpack version 2.77.2.1

This crash seemed to be caused by an error in Minecraft's EntityRenderer class while it was using lwjgl to draw entities.

**Comment by democat3457** [comment] 2020-09-10 21:07
@bboy122 @capio13 Does this happen on 2.77.5?

**Comment by democat3457** [comment] 2020-10-09 13:11
Closing for now.

**Closed by democat3457** 2020-10-09 13:11 UTC
Labels: needs testing, question
