### ISSUE TITLE
[BUG] Stone brick slabs drop stone brick slabs of wrong type

### ISSUE THREAD

**Issue by Jonesypunk** [Rebirth-of-the-Night/Rebirth-Of-The-Night#737] opened 2021-04-19 23:31 UTC
**Describe the bug**

breaking gneiss brick slabs with a pick drops red granite brick slabs
breaking a ecolite brick slab give black granite brick slab
marble > rhyolite
quartzite > andesite
migmatite > dacite
etc
red granite brick slab when broken still drops red granite brick slabs, same with black granite

**To Reproduce**  
break stone brick slabs in survival with any pickaxe (tested with bronze and soul steel)
**Expected behavior**

slab drops itself and not brick slab of different type
**Screenshots**

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [ x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [ x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [ x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

**Comment by democat3457** [comment] 2021-04-20 05:31
Duplicate of #362

**Closed by democat3457** 2021-04-20 05:31 UTC
