### ISSUE TITLE
[BUG] Inventory not saving properly on world exit

### ISSUE THREAD

**Issue by Tomato-No-Mae** [Rebirth-of-the-Night/Rebirth-Of-The-Night#782] opened 2021-07-05 01:34 UTC
**Describe the bug**
Your inventory from around 5-6 minutes before logging off of a world can overwrite your inventory at world save, deleting some items and duplicating ones that you put into chests.
This does not seem to affect non-player inventories.

**To Reproduce**  
1. Play in a world long enough for it to autosave
2. Save and exit
3. When this happened to me, i hopped into a creative test world directly after, so idk if that has anything to do with it
4. Join the world again
5. You should now have an older version of your inventory

**Expected behavior**
Inventory states to be updated when saving and exiting to the menu.

**Screenshots**
N/A

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [ x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [ x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [ x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**
might be an autosave setting or mod

**Comment by democat3457** [comment] 2022-03-10 23:39
Since it seems to be inconsistent and unable to be reproduced properly, I'll close this. If you find the root cause of it and can reproduce reliably, then feel free to re-open.

**Closed by democat3457** 2022-03-10 23:39 UTC
Labels: mod bug, 3.0 BETA
