### ISSUE TITLE
[BUG] Magnetism II Buff allows for certain Duplication Methods

### ISSUE THREAD

**Issue by Mozzy667** [Rebirth-of-the-Night/Rebirth-Of-The-Night#816] opened 2021-12-01 06:38 UTC
**Describe the bug**
Having Magnetism II while an item drops from either an npc or a block broken allows you to pick up a dozen more of the same item you were about to pick up

**To Reproduce**  
Method 1 -
1. Have a pet rat w/ the chef rat upgrade
2. Drink a Magnetism II potion
3. Give it Dragon Flesh in order to have it make Meat Feast pizza
4. Wait for it to finish and see results

Method 2 -
1. Place a chest down (I used a cabinet to do this)
2. Drink Magnetism II potion
3. Place any item inside the chest (or cabinet)
4. Break it and anything you put in the chest (along w/ the chest/cabinet) gets duplicated
Note: An axe or any tool w/ magnetic enchant bypasses the item dupe and only duplicates the chest

**Expected behavior**
I was expecting to give me just one of an item instantly without delay as the potion describes

**Screenshots**
https://cdn.discordapp.com/attachments/408367824508289026/915478680443158548/Pizzer.mp4 (video of me having Magnetism II before and after for comparison while Meat Feast Pizzas are being made for me to pick up)
https://cdn.discordapp.com/attachments/408367824508289026/915491262088499231/Funnydupe.mp4 (This one is pretty self-explanatory, Magnetism was already applied during the duration of this video)

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [X] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 

**Additional context**
I had a feeling it would be something tick related because that's what the potion description mentioned, I checked my in gamerule tickspeed and it was defaulted at a normal 3.

**Comment by democat3457** [comment] 2021-12-01 07:39
Fixed already, duplicate of #757

**Closed by democat3457** 2021-12-01 07:39 UTC
