### ISSUE TITLE
[BUG] Stygian End Biomes spawning in the Overworld 

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#558] opened 2021-01-11 06:30 UTC
**Describe the bug**
The Stygian End mod is configured to spawn Stygian End biomes in the overworld. These contain end stone along with wood that can be crafted in your 2x2 inventory. 

**To Reproduce**
1. Generate a random seed for RoTN 3.0 on a multiplayer world using the server pack. 
2. Fly around in an arbitrary direction. 
3. You will end up stumbling upon Stygian End biomes at a common rate as that of tainted biomes. 

**Expected behavior**
I expect players to not have access to that much easy end stone early on. 

**Screenshots**
![2021-01-09_23 12 45](https://user-images.githubusercontent.com/50285548/104151767-ad22c600-5392-11eb-8750-473735c7d3d2.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Multiplayer 
 - Version the world was created on: 3.0 Beta 2

**Additional context**
Check server pack configs.

**Comment by democat3457** [comment] 2021-01-11 15:44
which config

**Comment by KaleThyself** [comment] 2021-01-11 22:38
I didn't manage to find any helpful configs to change in Stygian's config file. 

After nearly an hour of flying around in a singleplayer world, I did not find any Stygian End biomes in the overworld. This may confirm that Stygian End biomes only spawn in the overworld in the server pack.

**Comment by CalaMariGold** [comment] 2021-01-15 22:25
@Foreck1 Give me a list of mods that could be responsible for this.

**Comment by Foreck1** [comment] 2021-01-15 22:34
@CalaMariGold 
GeographiCraft
Biomes o Plenty
Biome Tweaker

**Comment by CalaMariGold** [comment] 2021-01-15 22:42
Beginning to think this is an issue on Stygian's end. Likely a rare bug

**Comment by democat3457** [comment] 2021-01-15 22:45
Well, it doesn't seem rare if there are at least a few reports of it, and only happening on servers - additionally, we haven't updated the mod since what, 2.65, so reports of it only on 3.0 BETA probably means its on our end, in the server pack.

**Comment by CalaMariGold** [comment] 2021-01-15 22:47
The server pack is nearly identical to the client in terms of config

**Comment by CalaMariGold** [comment] 2021-01-15 23:04
I reproduced the issue after flying around in spectator on a server for 10 minutes

**Comment by CalaMariGold** [comment] 2021-01-15 23:06
No relevant information in the logs.

I'm at a loss here.

**Comment by CalaMariGold** [comment] 2021-01-19 23:22
Fixed in Beta 3. The issue was that The Beneath was missing from the server pack, which caused all biome IDs to be shifted over one, thus spawning the wrong biome in the Overworld.

**Closed by CalaMariGold** 2021-01-19 23:22 UTC
Labels: 3.0 BETA, RotN bug, awaiting information
