### ISSUE TITLE
[BUG] Trying to pick up lunar water with a bucket will result in a foamfix issue

### ISSUE THREAD

**Issue by aolinyang** [Rebirth-of-the-Night/Rebirth-Of-The-Night#845] opened 2022-04-16 21:30 UTC
### Describe the bug

Trying to pick up lunar water with a flimsy bucket will have a tooltip pop up "foamfix ran into an issue" and the bucket will say water bucket, but when you try to pour it the bucket just empties and nothing comes out.

### To Reproduce

1. Have a cauldron of lunar water
2. Try to scoop it up with a flimsy bucket
3. Try to pour the "water bucket"

### Expected behavior

No idea what the interaction should be

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by democat3457** [comment] 2022-04-21 00:56
dupe of #778

**Closed by democat3457** 2022-04-21 00:56 UTC
