### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by sakkezboi** [Rebirth-of-the-Night/Rebirth-Of-The-Night#735] opened 2021-04-17 15:22 UTC
**Describe the crash**
went into the twilight forest portal and its keeps on continuously crashing

**To Reproduce**  
Go to twilight forest

**Crash Log**
https://paste.dimdev.org/yawozadegi.mccrash

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 4
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 4
   - [ ] Other: 

**Additional context**
halp

**Comment by SenatorSupreme** [comment] 2021-04-17 15:25
Duplicate of #662

**Closed** 2021-04-17 15:26 UTC

**Comment by democat3457** [comment] 2021-04-17 20:29
also give it the duplicate label @SenatorSupreme

**Comment by SenatorSupreme** [comment] 2021-04-17 20:43
oh didn't know there was one, neat
