### ISSUE TITLE
Soapstone brick slabs, when mined, harvests as Komatiite brick slabs[BUG]

### ISSUE THREAD

**Issue by Halindrix** [Rebirth-of-the-Night/Rebirth-Of-The-Night#470] opened 2020-09-23 10:43 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: Place a soapstone brick slab down and harvest it with any pickaxe

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/71763357/94002204-987cdc80-fd67-11ea-8caa-469e84d78c3b.png)
![image](https://user-images.githubusercontent.com/71763357/94002231-9fa3ea80-fd67-11ea-8c67-96f215d53141.png)
![image](https://user-images.githubusercontent.com/71763357/94002250-a7fc2580-fd67-11ea-9d27-ca9197149c5f.png)
![image](https://user-images.githubusercontent.com/71763357/94002270-ad597000-fd67-11ea-9331-d489d9d39822.png)
![image](https://user-images.githubusercontent.com/71763357/94002309-b9ddc880-fd67-11ea-840c-3046c0d84705.png)
![image](https://user-images.githubusercontent.com/71763357/94002315-bcd8b900-fd67-11ea-827c-9f65e48b6ba4.png)
![image](https://user-images.githubusercontent.com/71763357/94002427-e265c280-fd67-11ea-9425-e869014b3205.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Both
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by democat3457** [comment] 2020-09-23 13:39
Duplicate of #362

**Closed by democat3457** 2020-09-23 13:39 UTC
