### ISSUE TITLE
Guards aggro'ing seemingly randomly, for no reason

### ISSUE THREAD

**Issue by Gunfly80** [Rebirth-of-the-Night/Rebirth-Of-The-Night#721] opened 2021-03-26 16:07 UTC
**Describe the bug**
<First occurred during my very first visit to a village (also first village I'd found). Despite having done nothing but just talking to people (did not break any crops, did not hit anyone, did not steal anything, made sure block in main hand was dirt and not a weapon), upon trying to talk to one of the plague doctors (was one of the ones with an actual mask), I was immediately attacked by at least 3 guards. Upon respawning, they still continued trying to kill me. I did not hit any of the guards during the attack, or try to defend myself. My reputation still showed as '0' 'neutral' like it had when I first entered the village, and did not change during the entire attack. After respawning after death 3 times, I grabbed what I could of my stuff and fled for my life.        After the most recent update within the past 2 days IRL, I was told that being attacked was a glitch and to try the village again. Upon entering the village again, my reputation still read as '0' 'neutral', and the guards left me alone. I was able to talk to people and take quests without being attacked, up until the last day in the village. That day cycle, I had done nothing beyond kill a goblin scavenger who was trying to kill one of the fletchers, talk to a farmer, and continue trying to build the wall around the village. Despite that, out of nowhere, I was shot off a wall by a guard on one of the towers, with no warning or chat dialogue. The guard continued trying to shoot at me while I was on the ground, but none of the other guards seemed to mind. It was just that particular guard this time, and I can't figure out what I did to piss them off. At the time of being shot at, my reputation read 'friendly' '80', and did not drop after being shot repeatedly by the guard. I haven't tried to retaliate in any way, and am currently hunkered down in an empty house on the edge of the village (villager died to a mob during one of the night cycles bc it wouldn't let me sleep). Am going to leave the village and return to base, because I don't know why the guard's mad at me, and it's making me worried that I'm going to get mobbed again and lose a bunch of the stuff I have on me. Any help as to what might be happening would be greatly appreciated, as I like interacting with villages and don't want to have to abandon this one because the guards randomly decide to attack me -->

**To Reproduce**  
   Returned to village after update that was described as having fixed the glitch, tried interacting with villagers again (had been behavior I had been performing at time of the first attack)
**Expected behavior**
<Expected guards to not attack me unless I'd done something to provoke them or if I'd broken one of the village rules>

**Screenshots**
< 
![image](https://user-images.githubusercontent.com/81432005/112659568-e4016780-8e2a-11eb-803a-eaeff63303b1.png)

(image description:  the guard trying to shoot at me, unprovoked, on the second visit. The arrows keep sticking into the railing since I managed to find a spot where he didn't have clear aim at me)
>

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 3.0 BETA 4
 - Server or Singleplayer:
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 3.0 BETA 3 (I think; date of world creation: 2/28/2021

**Additional context**
<  disclaimer that I'm a noob player and this is my first playthrough. For all I know, I could have broken some rule about interacting with plague doctors or villages in general and not known about it. But I have consistently tried to be as careful in the village as humanly possible, and have not hit anyone, stolen anything, or broken any crops. At this point, the only idea I have is that they might think I'm a mob because my skin is a badger, but I'm pretty sure that Rebirth doesn't have any sort of interaction trees with player appearance>

**Comment by democat3457** [comment] 2021-03-26 16:10
duplicate of #538

**Closed by democat3457** 2021-03-26 16:10 UTC

**Comment by Gunfly80** [comment] 2021-03-26 16:12
My bad; I didn't know it was a known bug. I've only started interacting with the discord and community within like the past week or so
