### ISSUE TITLE
[BUG] Unable to edit signs on chests

### ISSUE THREAD

**Issue by ZaneF77** [Rebirth-of-the-Night/Rebirth-Of-The-Night#374] opened 2020-06-08 08:12 UTC
**Describe the bug**
Unable to shift + right-click on signs placed on oak chests to edit the sign after initial typing on sign.

**To Reproduce**
Steps to reproduce the behavior: Place sign on oak chest with shift + right-click, type on sign, click done. Shift + right-click on sign to edit, nothing occurs.

**Expected behavior**
Expected to be able to edit text on the sign.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**
This was working in 2.77.4 but upon downloading the newest version and starting a new world it no longer works.

**Comment by SandwichHorror** [comment] 2020-06-12 20:21
You need an empty hand to edit the signs

**Comment by ZaneF77** [comment] 2020-06-13 07:27
> 
> 
> You need an empty hand to edit the signs

Having an empty hand does not make it work, with or without anything in my off-hand slot.

**Comment by Eksekk** [comment] 2020-06-13 13:01
Were you possibly flying on a hippogryph before? It often bugs out so you can't interact with objects (#121).

**Comment by democat3457** [comment] 2020-06-26 00:32
Also, did you try just right-clicking it without crouching?

**Comment by democat3457** [comment] 2020-07-06 00:41
Closing because I can't reproduce. Other than the fact that you need to right-click instead of shift-right-click.

**Closed by democat3457** 2020-07-06 00:41 UTC
Labels: needs testing, question
