### ISSUE TITLE
[CRASH] Game Crashed When Attacked by a Zombie

### ISSUE THREAD

**Issue by Power625** [Rebirth-of-the-Night/Rebirth-Of-The-Night#482] opened 2020-10-04 02:07 UTC
**Describe the crash**
Was climbing a mountain when a zombie fell on my head and hit me, causing my game to crash. Letting the zombie hit me again after loading back in did not cause another crash.

**To Reproduce**
Not sure. Maybe get hit by a falling zombie?

**Crash Log**
https://pastebin.com/CTRn8KqC

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**
The culprit:
![2020-10-03_21 14 33](https://user-images.githubusercontent.com/72326420/95005273-3b352680-05c4-11eb-8b9f-9ae33170bab2.png)

**Comment by democat3457** [comment] 2020-10-08 00:15
Duplicate of #296

**Closed by democat3457** 2020-10-08 00:15 UTC
