### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by GrozaMast** [Rebirth-of-the-Night/Rebirth-Of-The-Night#840] opened 2022-04-15 01:46 UTC
### Describe the crash

During the game, for some reason, the world collapsed. I survived peacefully, ran around the world at night and killed everyone in a row (it was the first day - suddenly it's important) But suddenly he flew into the menu, I had a throwing knife from a weapon and nothing else supernatural. In the crash menu it is written that somehow sideways the ice and fire mod may be to blame

### Crash Logs

[crash-2022-04-15_04.33.25-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/8493305/crash-2022-04-15_04.33.25-server.txt)

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

### Additional context

I would also like to ask you while I have the opportunity. Is it possible to play this build together over a local network, or will something break?

**Comment by TheNelston** [comment] 2022-04-15 15:13
looks like a ticking world issue caused by an ice and fire snow villager, id recommend checking this link for how to fix it (scroll down to cofh core): https://nodecraft.com/support/games/minecraft/fixing-ticking-entities-errors-in-minecraft

**Comment by democat3457** [comment] 2022-04-15 23:47
This is actually a bug with IaF. If I can get my dev environment for IaF working, I can fix this - otherwise, the error will continue occurring with other instances of Snow Villagers.

**Comment by democat3457** [comment] 2022-05-05 01:05
Fixed with https://github.com/Rebirth-of-the-Night/Ice_and_Fire/pull/21

**Closed by democat3457** 2022-05-05 01:05 UTC
Labels: mod bug, 3.0.0 Release
