### ISSUE TITLE
[BUG] Naturally spawning blocks "Two Masonry Bricks!" Appears without a texture

### ISSUE THREAD

**Issue by Unishine** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1050] opened 2023-08-20 00:02 UTC
### Describe the bug

When hovering over "Two Masonry Bricks!" it will appear without a texture on the bottom left of my screen.

### To Reproduce

Find a naturally spawning masonry brick location (??) I kinda just found it in my world.

### Expected behavior

To see the two bricks in its 3d form at the bottom left.

### Screenshots

![2023-08-19_19 52 59](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/assets/101996181/21d4e222-bf71-47b4-a32e-fa0717160116)
![2023-08-19_19 53 22](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/assets/101996181/839d24b8-4f83-49d7-802f-73ed656f024e)

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

### Additional context

My guess is that the block was never meant to be holdable, so it was never given a texture by its original mod creator.

**Comment by Foreck1** [comment] 2024-03-26 06:53
Duplicate of #1078

**Closed by Foreck1** 2024-03-26 06:53 UTC
