### ISSUE TITLE
[BUG] Cyclic fluid dupe bug

### ISSUE THREAD

**Issue by Dr-Turtle** [Rebirth-of-the-Night/Rebirth-Of-The-Night#798] opened 2021-09-01 13:53 UTC
**Describe the bug**
Infinite amounts of any liquid can be obtained when flowing fluid is adjacent to a fluid pipe with any liquid.

**To Reproduce**  
1. Place a cyclic fluid extractor on a liquid barrel (or another fluid storage block) filled with water (or any other fluid)
2. Place a single fluid pipe next to the fluid extractor
3. Place a fluid source so that it flows into a block adjacent to the fluid pipe.
4. The flowing fluid next to the fluid pipe will turn into a source block, quickly draining the pipe of its contents.

**Expected behavior**
The fluid pipe should not interact with adjacent fluids.

**Screenshots**
https://imgur.com/a/xZ0frU3

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [x] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**
I tested this in an instance with only cyclic installed, and the same behavior was present; however, cyclic 1.12.2 is no longer supported, so reporting this on the cyclic github would likely not lead to a fix.

**Comment by democat3457** [comment] 2021-09-04 03:46
duplicate of #769

**Closed by democat3457** 2021-09-04 03:46 UTC
